
package cn.itcast.export.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExportServiceService", targetNamespace = "http://webservice.export.itcast.cn/", wsdlLocation = "http://localhost:8080/jk_export/ws/export?wsdl")
public class ExportServiceService
    extends Service
{

    private final static URL EXPORTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EXPORTSERVICESERVICE_EXCEPTION;
    private final static QName EXPORTSERVICESERVICE_QNAME = new QName("http://webservice.export.itcast.cn/", "ExportServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jk_export/ws/export?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXPORTSERVICESERVICE_WSDL_LOCATION = url;
        EXPORTSERVICESERVICE_EXCEPTION = e;
    }

    public ExportServiceService() {
        super(__getWsdlLocation(), EXPORTSERVICESERVICE_QNAME);
    }

    public ExportServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXPORTSERVICESERVICE_QNAME, features);
    }

    public ExportServiceService(URL wsdlLocation) {
        super(wsdlLocation, EXPORTSERVICESERVICE_QNAME);
    }

    public ExportServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXPORTSERVICESERVICE_QNAME, features);
    }

    public ExportServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExportServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExportService
     */
    @WebEndpoint(name = "ExportServicePort")
    public ExportService getExportServicePort() {
        return super.getPort(new QName("http://webservice.export.itcast.cn/", "ExportServicePort"), ExportService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExportService
     */
    @WebEndpoint(name = "ExportServicePort")
    public ExportService getExportServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.export.itcast.cn/", "ExportServicePort"), ExportService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXPORTSERVICESERVICE_EXCEPTION!= null) {
            throw EXPORTSERVICESERVICE_EXCEPTION;
        }
        return EXPORTSERVICESERVICE_WSDL_LOCATION;
    }

}
